### PR TITLE
[WIP] Upgrade to nanoc 4

### PR DESCRIPTION
**Pull request by ddfreyne**
This upgrades the GitHub developer site from nanoc 3.x to nanoc 4, and makes use of the new features in nanoc 4 (identifiers with extensions, and globs).

For details on nanoc 4, see the [nanoc 4 upgrade guide](http://nanoc.ws/docs/nanoc-4-upgrade-guide/).

I’ve opted for an approach that keeps the number of changes small. There is some future work that can be done to improve the site in terms of maintainability—see the _Future work_ section below for details.

Compilation speed is expected to be similar, but after switching to globs and identifiers with extension, compilation speed will be significantly lower. This is because there are no optimisations for finding items by globs yet.

* [ ] Use Nanoc 4 final in Gemfile
* [ ] Re-add the Ruby version declaration in Gemfile
* [x] Go through changes in detail and make sure everything is okay
  * [x] Fix `output/changes/index.html`

Future work:

* Reduce duplication in layouts.

* Move _static/_ into content and thereby simplify rules.

* Move search filter into normal nanoc workflow. (Idea: let each searchable item have a `search` representation, and have a `search-json` item that collects all these.)

### CODE REVIEW

**Comment by ddfreyne** [comment]
Finding a layout, given a string, could be modified to do the following:

1. Try to find a layout whose identifier is exactly the same as the given string.

2. Try to find a layout whose identifier is exactly the same as the given string, converted to a “cleaned up” old-style identifier (e.g. `"head"` becomes `"/head/"`).

3. If the given string does not have any glob characters (any of `* [ ] { } ,`), prefix it with `/` and postfix it with `.*`, and try to find a layout whose identifier matches the resulting string.

4. If the given string has some glob characters (any of `* [ ] { } ,`), try to find a layout whose identifier matches the given string.

**Comment by ddfreyne** [comment]
Will Soon™ rebase this on master (likely once Nanoc 4 final is out).

This isn’t up-to-date with Nanoc 4 RC 3 yet; it uses `#with_ext` which was removed due to it having confusing behavior. Upgrading it to Nanoc 4 RC 3 shouldn’t be more work than replacing `#with_ext`.

**Comment by ddfreyne** [comment]
This is now up-to-date with `master` of `github/developer.github.com`.

**Comment by ddfreyne** [comment]
Nanoc 4:

```
Site compiled in 19.76s.
```

Nanoc 3:

```
Site compiled in 17.67s.
````

Some slowdown in Nanoc 4 is expected, but it’s not nearly as bad as I thought. Hurrah!

**Comment by ddfreyne** [comment]
CC @gjtorikian — Does it make sense to open a PR on github/developer.github.com with my changes to upgrade the site to Nanoc 4, or would you rather wait?

**Comment by gjtorikian** [comment]
I think opening the PR right now is grand. When do you anticipate 4.0 will bring out? I've already begun building something with it and the rc3 release seems very stable.

**Comment by ddfreyne** [comment]
I plan on releasing Nanoc 4 final some time in the next few days!

PR opened: github/developer.github.com#886

**Comment by ddfreyne** [comment]
Closed in favour of github/developer.github.com#886.

**Pull request closed without merging**
